{{- if .Values.airflow.dags.gitSync.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.airflow.dags.gitSync.httpSecret }}
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.airflow.dags.gitSync.httpSecretUsernameKey }}: {{ .Values.airflow.dags.gitSync.username }}
  {{ .Values.airflow.dags.gitSync.httpSecretPasswordKey }}: {{ .Values.airflow.dags.gitSync.token }}

{{- end }}