apiVersion: v1
kind: Secret
metadata:
  name: airflow-password-secret
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.security.password }}

